### ISSUE TITLE
Cropping Image Changes Transparent Background To Solid Color

### ISSUE THREAD

**Issue by Jim-Webfox** [flyimg/flyimg#514]
When taking an image with a transparent background, after resizing, cropping and setting output to png, a solid background is added to the image, it is no longer transparent.  

Failing Result
https://demo.flyimg.io/upload/w_100,h_50,c_1,o_png/https://brandslogos.com/wp-content/uploads/images/large/laravel-logo-1.png

The image should maintain its transparent background.

![image](https://github.com/user-attachments/assets/76a14def-e6a9-40bd-862f-530be970849b)

**Comment by sadok-f** [comment]
Hi @Jim-Webfox ,
Thank you for opening this issue!

Yes, it seems the crop option adds a black background to the generated image.
I'll check it and I'll keep you updated.

**Comment by sadok-f** [comment]
@Jim-Webfox can you try again? I've deployed a new version with a potential fix.
since we're using the `extent` option to match the desired size given, we need to add `-background none` to remove the added background (black in your case).

**Comment by Jim-Webfox** [comment]
@sadok-f Thanks for jumping on this so quickly!

It appears that its still happening. The link I provided in the initial issue still shows this, unless its using an old version of flyimg on the demo site?

**Comment by Jim-Webfox** [comment]
Ah good to know in future!

**Comment by sadok-f** [comment]
I think I know what is happening, its not a bug.

Recently we started running the demo page on a docker swarm cluster, where the nodes are not sharing the cache nor the generated images folders.

So the rf_1 option should hit all of the nodes to get the refreshed generated image.

**Comment by Jim-Webfox** [comment]
It Works!

https://demo.flyimg.io/upload/w_100,h_50,c_1,r_1,o_png/https://brandslogos.com/wp-content/uploads/images/large/laravel-logo-1.png

**Comment by Jim-Webfox** [comment]
Oh its rf_1 not r_1?

**Comment by Jim-Webfox** [comment]
ah still works

https://demo.flyimg.io/upload/w_100,h_50,c_1,rf_1,o_png/https://brandslogos.com/wp-content/uploads/images/large/laravel-logo-1.png

**Comment by Jim-Webfox** [comment]
Im happy, if your happy also we can close this issue.

Thank you
